{
 "title": "Bess",
 "description": "Current IN",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ds", "label": "Data Source", "query": "influxdb" }
  ]
 },
 "panels": [
  {
   "title": "Bess",
   "type": "gauge",
   "gridPos": { "h": 18, "w": 4, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "bess",
     "query": "SELECT last(\"ac_current_in\") as \"AC Current Input\" FROM \"bess\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "ac_current_in" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "bess",
     "query": "SELECT last(\"ac_current_out\")  AS \"AC Current Output\"FROM \"bess\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "ac_current_out" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Battery 1 - Power",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "voltamp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "current",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "pcs",
     "select": [
      [
       { "params": [ "dc_current" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "group_id::tag", "operator": "=", "value": "1" },
      { "condition": "AND", "key": "id::tag", "operator": "=", "value": "1" }
     ]
    },
    {
     "alias": "voltage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "pcs",
     "select": [
      [
       { "params": [ "dc_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "group_id::tag", "operator": "=", "value": "1" },
      { "condition": "AND", "key": "id::tag", "operator": "=", "value": "1" }
     ]
    }
   ]
  },
  {
   "title": "Battery 1 -SOC",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "battery",
     "query": "SELECT last(\"soc\") as \"Battery 1\" FROM \"battery\" WHERE (\"group_id\"::tag = '1') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "soc" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "group_id::tag", "operator": "=", "value": "1" }
     ]
    }
   ]
  },
  {
   "title": "Battery 2 - DC",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "DC Current",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pcs",
     "query": "SELECT last(\"ac_current\") AS \"AC Current\" FROM \"pcs\" WHERE (\"group_id\"::tag = '1') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "dc_current" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "group_id::tag", "operator": "=", "value": "2" },
      { "condition": "AND", "key": "id::tag", "operator": "=", "value": "2" }
     ]
    },
    {
     "alias": "DC Voltage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pcs",
     "query": "SELECT last(\"ac_current\") AS \"AC Current\" FROM \"pcs\" WHERE (\"group_id\"::tag = '1') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "dc_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "group_id::tag", "operator": "=", "value": "2" },
      { "condition": "AND", "key": "id::tag", "operator": "=", "value": "2" }
     ]
    }
   ]
  },
  {
   "title": "Battery 1 - AC",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 3, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Current A",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pcs",
     "query": "SELECT last(\"ac_a_current\")  / 1000  FROM \"pcs\" WHERE (\"group_id\"::tag = '2' AND \"id\"::tag = '2') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "ac_a_current" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "group_id::tag", "operator": "=", "value": "1" },
      { "condition": "AND", "key": "id::tag", "operator": "=", "value": "1" }
     ]
    },
    {
     "alias": "Current B",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pcs",
     "query": "SELECT last(\"ac_b_current\")  / 1000 FROM \"pcs\" WHERE (\"group_id\"::tag = '1' AND \"id\"::tag = '1') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "ac_b_current" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "group_id::tag", "operator": "=", "value": "2" },
      { "condition": "AND", "key": "id::tag", "operator": "=", "value": "2" }
     ]
    },
    {
     "alias": "Current C",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pcs",
     "query": "SELECT last(\"ac_c_current\")  / 1000 FROM \"pcs\" WHERE (\"group_id\"::tag = '1' AND \"id\"::tag = '1') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "ac_c_current" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "group_id::tag", "operator": "=", "value": "2" },
      { "condition": "AND", "key": "id::tag", "operator": "=", "value": "2" }
     ]
    },
    {
     "alias": "Voltage A",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pcs",
     "query": "SELECT last(\"ac_a_voltage\")  / 1000 FROM \"pcs\" WHERE (\"group_id\"::tag = '1' AND \"id\"::tag = '1') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "ac_a_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "group_id::tag", "operator": "=", "value": "2" },
      { "condition": "AND", "key": "id::tag", "operator": "=", "value": "2" }
     ]
    },
    {
     "alias": "Voltage B",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pcs",
     "query": "SELECT last(\"ac_b_voltage\")  / 1000 FROM \"pcs\" WHERE (\"group_id\"::tag = '1' AND \"id\"::tag = '1') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "ac_b_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "group_id::tag", "operator": "=", "value": "2" },
      { "condition": "AND", "key": "id::tag", "operator": "=", "value": "2" }
     ]
    },
    {
     "alias": "Voltage C",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pcs",
     "query": "SELECT last(\"ac_c_voltage\")  / 1000 FROM \"pcs\" WHERE (\"group_id\"::tag = '1' AND \"id\"::tag = '1') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "ac_c_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "group_id::tag", "operator": "=", "value": "2" },
      { "condition": "AND", "key": "id::tag", "operator": "=", "value": "2" }
     ]
    }
   ]
  },
  {
   "title": "Battery 2 - Power",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "voltamp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "current",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "pcs",
     "select": [
      [
       { "params": [ "dc_current" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "group_id::tag", "operator": "=", "value": "2" },
      { "condition": "AND", "key": "id::tag", "operator": "=", "value": "2" }
     ]
    },
    {
     "alias": "voltage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "pcs",
     "select": [
      [
       { "params": [ "dc_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "group_id::tag", "operator": "=", "value": "2" },
      { "condition": "AND", "key": "id::tag", "operator": "=", "value": "2" }
     ]
    }
   ]
  },
  {
   "title": "Battery 2 - SOC",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 10, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "battery",
     "query": "SELECT last(\"soc\")  as \"Battery 2\" FROM \"battery\" WHERE (\"group_id\"::tag = '2') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "current" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "group_id::tag", "operator": "=", "value": "2" }
     ]
    }
   ]
  },
  {
   "title": "Battery 1 - DC",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 5, "x": 14, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "DC Current",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pcs",
     "query": "SELECT last(\"ac_current\") AS \"AC Current\" FROM \"pcs\" WHERE (\"group_id\"::tag = '1') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "dc_current" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "group_id::tag", "operator": "=", "value": "1" },
      { "condition": "AND", "key": "id::tag", "operator": "=", "value": "1" }
     ]
    },
    {
     "alias": "DC Voltage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pcs",
     "query": "SELECT last(\"ac_current\") AS \"AC Current\" FROM \"pcs\" WHERE (\"group_id\"::tag = '1') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "dc_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "group_id::tag", "operator": "=", "value": "1" },
      { "condition": "AND", "key": "id::tag", "operator": "=", "value": "1" }
     ]
    }
   ]
  },
  {
   "title": "Battery 2 - AC",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 3, "x": 19, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Current A",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pcs",
     "query": "SELECT last(\"ac_a_current\")  / 1000  FROM \"pcs\" WHERE (\"group_id\"::tag = '2' AND \"id\"::tag = '2') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "ac_a_current" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "group_id::tag", "operator": "=", "value": "2" },
      { "condition": "AND", "key": "id::tag", "operator": "=", "value": "2" }
     ]
    },
    {
     "alias": "Current B",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pcs",
     "query": "SELECT last(\"ac_a_current\")  / 1000  FROM \"pcs\" WHERE (\"group_id\"::tag = '2' AND \"id\"::tag = '2') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "ac_b_current" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "group_id::tag", "operator": "=", "value": "2" },
      { "condition": "AND", "key": "id::tag", "operator": "=", "value": "2" }
     ]
    },
    {
     "alias": "Current C",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pcs",
     "query": "SELECT last(\"ac_a_current\")  / 1000  FROM \"pcs\" WHERE (\"group_id\"::tag = '2' AND \"id\"::tag = '2') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "ac_c_current" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "group_id::tag", "operator": "=", "value": "2" },
      { "condition": "AND", "key": "id::tag", "operator": "=", "value": "2" }
     ]
    },
    {
     "alias": "Voltage A",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pcs",
     "query": "SELECT last(\"ac_a_current\")  / 1000  FROM \"pcs\" WHERE (\"group_id\"::tag = '2' AND \"id\"::tag = '2') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "ac_a_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "group_id::tag", "operator": "=", "value": "2" },
      { "condition": "AND", "key": "id::tag", "operator": "=", "value": "2" }
     ]
    },
    {
     "alias": "Voltage B",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pcs",
     "query": "SELECT last(\"ac_a_current\")  / 1000  FROM \"pcs\" WHERE (\"group_id\"::tag = '2' AND \"id\"::tag = '2') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "ac_b_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "group_id::tag", "operator": "=", "value": "2" },
      { "condition": "AND", "key": "id::tag", "operator": "=", "value": "2" }
     ]
    },
    {
     "alias": "Voltage C",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pcs",
     "query": "SELECT last(\"ac_a_current\")  / 1000  FROM \"pcs\" WHERE (\"group_id\"::tag = '2' AND \"id\"::tag = '2') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "ac_c_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "group_id::tag", "operator": "=", "value": "2" },
      { "condition": "AND", "key": "id::tag", "operator": "=", "value": "2" }
     ]
    }
   ]
  }
 ]
}